// 세계 각국의 수도 데이터 (UN 회원국 기준)
// alt: 주관식 모드에서 함께 정답으로 인정되는 표기
const COUNTRIES = [
  // ── 아시아 ──────────────────────────────────────────────
  { country: "대한민국", countryEn: "South Korea", capital: "서울", capitalEn: "Seoul", region: "아시아", alt: ["서울특별시"] },
  { country: "북한", countryEn: "North Korea", capital: "평양", capitalEn: "Pyongyang", region: "아시아" },
  { country: "일본", countryEn: "Japan", capital: "도쿄", capitalEn: "Tokyo", region: "아시아" },
  { country: "중국", countryEn: "China", capital: "베이징", capitalEn: "Beijing", region: "아시아", alt: ["북경"] },
  { country: "몽골", countryEn: "Mongolia", capital: "울란바토르", capitalEn: "Ulaanbaatar", region: "아시아" },
  { country: "베트남", countryEn: "Vietnam", capital: "하노이", capitalEn: "Hanoi", region: "아시아" },
  { country: "라오스", countryEn: "Laos", capital: "비엔티안", capitalEn: "Vientiane", region: "아시아" },
  { country: "캄보디아", countryEn: "Cambodia", capital: "프놈펜", capitalEn: "Phnom Penh", region: "아시아" },
  { country: "태국", countryEn: "Thailand", capital: "방콕", capitalEn: "Bangkok", region: "아시아" },
  { country: "미얀마", countryEn: "Myanmar", capital: "네피도", capitalEn: "Naypyidaw", region: "아시아" },
  { country: "말레이시아", countryEn: "Malaysia", capital: "쿠알라룸푸르", capitalEn: "Kuala Lumpur", region: "아시아" },
  { country: "싱가포르", countryEn: "Singapore", capital: "싱가포르", capitalEn: "Singapore", region: "아시아" },
  { country: "인도네시아", countryEn: "Indonesia", capital: "자카르타", capitalEn: "Jakarta", region: "아시아", alt: ["누산타라"] },
  { country: "필리핀", countryEn: "Philippines", capital: "마닐라", capitalEn: "Manila", region: "아시아" },
  { country: "브루나이", countryEn: "Brunei", capital: "반다르스리브가완", capitalEn: "Bandar Seri Begawan", region: "아시아" },
  { country: "동티모르", countryEn: "Timor-Leste", capital: "딜리", capitalEn: "Dili", region: "아시아" },
  { country: "인도", countryEn: "India", capital: "뉴델리", capitalEn: "New Delhi", region: "아시아" },
  { country: "파키스탄", countryEn: "Pakistan", capital: "이슬라마바드", capitalEn: "Islamabad", region: "아시아" },
  { country: "방글라데시", countryEn: "Bangladesh", capital: "다카", capitalEn: "Dhaka", region: "아시아" },
  { country: "네팔", countryEn: "Nepal", capital: "카트만두", capitalEn: "Kathmandu", region: "아시아" },
  { country: "부탄", countryEn: "Bhutan", capital: "팀부", capitalEn: "Thimphu", region: "아시아" },
  { country: "스리랑카", countryEn: "Sri Lanka", capital: "스리자야와르데네푸라코테", capitalEn: "Sri Jayawardenepura Kotte", region: "아시아", alt: ["콜롬보"] },
  { country: "몰디브", countryEn: "Maldives", capital: "말레", capitalEn: "Malé", region: "아시아" },
  { country: "아프가니스탄", countryEn: "Afghanistan", capital: "카불", capitalEn: "Kabul", region: "아시아" },
  { country: "이란", countryEn: "Iran", capital: "테헤란", capitalEn: "Tehran", region: "아시아" },
  { country: "이라크", countryEn: "Iraq", capital: "바그다드", capitalEn: "Baghdad", region: "아시아" },
  { country: "시리아", countryEn: "Syria", capital: "다마스쿠스", capitalEn: "Damascus", region: "아시아" },
  { country: "레바논", countryEn: "Lebanon", capital: "베이루트", capitalEn: "Beirut", region: "아시아" },
  { country: "요르단", countryEn: "Jordan", capital: "암만", capitalEn: "Amman", region: "아시아" },
  { country: "이스라엘", countryEn: "Israel", capital: "예루살렘", capitalEn: "Jerusalem", region: "아시아" },
  { country: "사우디아라비아", countryEn: "Saudi Arabia", capital: "리야드", capitalEn: "Riyadh", region: "아시아" },
  { country: "예멘", countryEn: "Yemen", capital: "사나", capitalEn: "Sanaa", region: "아시아" },
  { country: "오만", countryEn: "Oman", capital: "무스카트", capitalEn: "Muscat", region: "아시아" },
  { country: "아랍에미리트", countryEn: "United Arab Emirates", capital: "아부다비", capitalEn: "Abu Dhabi", region: "아시아" },
  { country: "카타르", countryEn: "Qatar", capital: "도하", capitalEn: "Doha", region: "아시아" },
  { country: "바레인", countryEn: "Bahrain", capital: "마나마", capitalEn: "Manama", region: "아시아" },
  { country: "쿠웨이트", countryEn: "Kuwait", capital: "쿠웨이트시티", capitalEn: "Kuwait City", region: "아시아", alt: ["쿠웨이트"] },
  { country: "튀르키예", countryEn: "Türkiye", capital: "앙카라", capitalEn: "Ankara", region: "아시아" },
  { country: "조지아", countryEn: "Georgia", capital: "트빌리시", capitalEn: "Tbilisi", region: "아시아" },
  { country: "아르메니아", countryEn: "Armenia", capital: "예레반", capitalEn: "Yerevan", region: "아시아" },
  { country: "아제르바이잔", countryEn: "Azerbaijan", capital: "바쿠", capitalEn: "Baku", region: "아시아" },
  { country: "카자흐스탄", countryEn: "Kazakhstan", capital: "아스타나", capitalEn: "Astana", region: "아시아" },
  { country: "우즈베키스탄", countryEn: "Uzbekistan", capital: "타슈켄트", capitalEn: "Tashkent", region: "아시아" },
  { country: "투르크메니스탄", countryEn: "Turkmenistan", capital: "아시가바트", capitalEn: "Ashgabat", region: "아시아" },
  { country: "키르기스스탄", countryEn: "Kyrgyzstan", capital: "비슈케크", capitalEn: "Bishkek", region: "아시아" },
  { country: "타지키스탄", countryEn: "Tajikistan", capital: "두샨베", capitalEn: "Dushanbe", region: "아시아" },

  // ── 유럽 ────────────────────────────────────────────────
  { country: "영국", countryEn: "United Kingdom", capital: "런던", capitalEn: "London", region: "유럽" },
  { country: "아일랜드", countryEn: "Ireland", capital: "더블린", capitalEn: "Dublin", region: "유럽" },
  { country: "프랑스", countryEn: "France", capital: "파리", capitalEn: "Paris", region: "유럽" },
  { country: "독일", countryEn: "Germany", capital: "베를린", capitalEn: "Berlin", region: "유럽" },
  { country: "이탈리아", countryEn: "Italy", capital: "로마", capitalEn: "Rome", region: "유럽" },
  { country: "스페인", countryEn: "Spain", capital: "마드리드", capitalEn: "Madrid", region: "유럽" },
  { country: "포르투갈", countryEn: "Portugal", capital: "리스본", capitalEn: "Lisbon", region: "유럽" },
  { country: "네덜란드", countryEn: "Netherlands", capital: "암스테르담", capitalEn: "Amsterdam", region: "유럽" },
  { country: "벨기에", countryEn: "Belgium", capital: "브뤼셀", capitalEn: "Brussels", region: "유럽" },
  { country: "룩셈부르크", countryEn: "Luxembourg", capital: "룩셈부르크", capitalEn: "Luxembourg", region: "유럽" },
  { country: "스위스", countryEn: "Switzerland", capital: "베른", capitalEn: "Bern", region: "유럽" },
  { country: "오스트리아", countryEn: "Austria", capital: "빈", capitalEn: "Vienna", region: "유럽" },
  { country: "덴마크", countryEn: "Denmark", capital: "코펜하겐", capitalEn: "Copenhagen", region: "유럽" },
  { country: "노르웨이", countryEn: "Norway", capital: "오슬로", capitalEn: "Oslo", region: "유럽" },
  { country: "스웨덴", countryEn: "Sweden", capital: "스톡홀름", capitalEn: "Stockholm", region: "유럽" },
  { country: "핀란드", countryEn: "Finland", capital: "헬싱키", capitalEn: "Helsinki", region: "유럽" },
  { country: "아이슬란드", countryEn: "Iceland", capital: "레이캬비크", capitalEn: "Reykjavík", region: "유럽" },
  { country: "폴란드", countryEn: "Poland", capital: "바르샤바", capitalEn: "Warsaw", region: "유럽" },
  { country: "체코", countryEn: "Czechia", capital: "프라하", capitalEn: "Prague", region: "유럽" },
  { country: "슬로바키아", countryEn: "Slovakia", capital: "브라티슬라바", capitalEn: "Bratislava", region: "유럽" },
  { country: "헝가리", countryEn: "Hungary", capital: "부다페스트", capitalEn: "Budapest", region: "유럽" },
  { country: "루마니아", countryEn: "Romania", capital: "부쿠레슈티", capitalEn: "Bucharest", region: "유럽" },
  { country: "불가리아", countryEn: "Bulgaria", capital: "소피아", capitalEn: "Sofia", region: "유럽" },
  { country: "그리스", countryEn: "Greece", capital: "아테네", capitalEn: "Athens", region: "유럽" },
  { country: "크로아티아", countryEn: "Croatia", capital: "자그레브", capitalEn: "Zagreb", region: "유럽" },
  { country: "슬로베니아", countryEn: "Slovenia", capital: "류블랴나", capitalEn: "Ljubljana", region: "유럽" },
  { country: "세르비아", countryEn: "Serbia", capital: "베오그라드", capitalEn: "Belgrade", region: "유럽" },
  { country: "보스니아 헤르체고비나", countryEn: "Bosnia and Herzegovina", capital: "사라예보", capitalEn: "Sarajevo", region: "유럽" },
  { country: "몬테네그로", countryEn: "Montenegro", capital: "포드고리차", capitalEn: "Podgorica", region: "유럽" },
  { country: "북마케도니아", countryEn: "North Macedonia", capital: "스코페", capitalEn: "Skopje", region: "유럽" },
  { country: "알바니아", countryEn: "Albania", capital: "티라나", capitalEn: "Tirana", region: "유럽" },
  { country: "우크라이나", countryEn: "Ukraine", capital: "키이우", capitalEn: "Kyiv", region: "유럽", alt: ["키예프"] },
  { country: "벨라루스", countryEn: "Belarus", capital: "민스크", capitalEn: "Minsk", region: "유럽" },
  { country: "몰도바", countryEn: "Moldova", capital: "키시나우", capitalEn: "Chisinau", region: "유럽" },
  { country: "러시아", countryEn: "Russia", capital: "모스크바", capitalEn: "Moscow", region: "유럽" },
  { country: "에스토니아", countryEn: "Estonia", capital: "탈린", capitalEn: "Tallinn", region: "유럽" },
  { country: "라트비아", countryEn: "Latvia", capital: "리가", capitalEn: "Riga", region: "유럽" },
  { country: "리투아니아", countryEn: "Lithuania", capital: "빌뉴스", capitalEn: "Vilnius", region: "유럽" },
  { country: "몰타", countryEn: "Malta", capital: "발레타", capitalEn: "Valletta", region: "유럽" },
  { country: "키프로스", countryEn: "Cyprus", capital: "니코시아", capitalEn: "Nicosia", region: "유럽" },
  { country: "안도라", countryEn: "Andorra", capital: "안도라라베야", capitalEn: "Andorra la Vella", region: "유럽" },
  { country: "모나코", countryEn: "Monaco", capital: "모나코", capitalEn: "Monaco", region: "유럽" },
  { country: "산마리노", countryEn: "San Marino", capital: "산마리노", capitalEn: "San Marino", region: "유럽" },
  { country: "리히텐슈타인", countryEn: "Liechtenstein", capital: "파두츠", capitalEn: "Vaduz", region: "유럽" },

  // ── 아프리카 ────────────────────────────────────────────
  { country: "이집트", countryEn: "Egypt", capital: "카이로", capitalEn: "Cairo", region: "아프리카" },
  { country: "리비아", countryEn: "Libya", capital: "트리폴리", capitalEn: "Tripoli", region: "아프리카" },
  { country: "튀니지", countryEn: "Tunisia", capital: "튀니스", capitalEn: "Tunis", region: "아프리카" },
  { country: "알제리", countryEn: "Algeria", capital: "알제", capitalEn: "Algiers", region: "아프리카" },
  { country: "모로코", countryEn: "Morocco", capital: "라바트", capitalEn: "Rabat", region: "아프리카" },
  { country: "수단", countryEn: "Sudan", capital: "하르툼", capitalEn: "Khartoum", region: "아프리카" },
  { country: "남수단", countryEn: "South Sudan", capital: "주바", capitalEn: "Juba", region: "아프리카" },
  { country: "에티오피아", countryEn: "Ethiopia", capital: "아디스아바바", capitalEn: "Addis Ababa", region: "아프리카" },
  { country: "에리트레아", countryEn: "Eritrea", capital: "아스마라", capitalEn: "Asmara", region: "아프리카" },
  { country: "지부티", countryEn: "Djibouti", capital: "지부티", capitalEn: "Djibouti", region: "아프리카" },
  { country: "소말리아", countryEn: "Somalia", capital: "모가디슈", capitalEn: "Mogadishu", region: "아프리카" },
  { country: "케냐", countryEn: "Kenya", capital: "나이로비", capitalEn: "Nairobi", region: "아프리카" },
  { country: "우간다", countryEn: "Uganda", capital: "캄팔라", capitalEn: "Kampala", region: "아프리카" },
  { country: "르완다", countryEn: "Rwanda", capital: "키갈리", capitalEn: "Kigali", region: "아프리카" },
  { country: "부룬디", countryEn: "Burundi", capital: "기테가", capitalEn: "Gitega", region: "아프리카" },
  { country: "탄자니아", countryEn: "Tanzania", capital: "도도마", capitalEn: "Dodoma", region: "아프리카" },
  { country: "콩고민주공화국", countryEn: "DR Congo", capital: "킨샤사", capitalEn: "Kinshasa", region: "아프리카" },
  { country: "콩고공화국", countryEn: "Republic of the Congo", capital: "브라자빌", capitalEn: "Brazzaville", region: "아프리카" },
  { country: "중앙아프리카공화국", countryEn: "Central African Republic", capital: "방기", capitalEn: "Bangui", region: "아프리카" },
  { country: "차드", countryEn: "Chad", capital: "은자메나", capitalEn: "N'Djamena", region: "아프리카" },
  { country: "니제르", countryEn: "Niger", capital: "니아메", capitalEn: "Niamey", region: "아프리카" },
  { country: "나이지리아", countryEn: "Nigeria", capital: "아부자", capitalEn: "Abuja", region: "아프리카" },
  { country: "베냉", countryEn: "Benin", capital: "포르토노보", capitalEn: "Porto-Novo", region: "아프리카" },
  { country: "토고", countryEn: "Togo", capital: "로메", capitalEn: "Lomé", region: "아프리카" },
  { country: "가나", countryEn: "Ghana", capital: "아크라", capitalEn: "Accra", region: "아프리카" },
  { country: "코트디부아르", countryEn: "Côte d'Ivoire", capital: "야무수크로", capitalEn: "Yamoussoukro", region: "아프리카" },
  { country: "라이베리아", countryEn: "Liberia", capital: "몬로비아", capitalEn: "Monrovia", region: "아프리카" },
  { country: "시에라리온", countryEn: "Sierra Leone", capital: "프리타운", capitalEn: "Freetown", region: "아프리카" },
  { country: "기니", countryEn: "Guinea", capital: "코나크리", capitalEn: "Conakry", region: "아프리카" },
  { country: "기니비사우", countryEn: "Guinea-Bissau", capital: "비사우", capitalEn: "Bissau", region: "아프리카" },
  { country: "세네갈", countryEn: "Senegal", capital: "다카르", capitalEn: "Dakar", region: "아프리카" },
  { country: "감비아", countryEn: "Gambia", capital: "반줄", capitalEn: "Banjul", region: "아프리카" },
  { country: "모리타니", countryEn: "Mauritania", capital: "누악쇼트", capitalEn: "Nouakchott", region: "아프리카" },
  { country: "말리", countryEn: "Mali", capital: "바마코", capitalEn: "Bamako", region: "아프리카" },
  { country: "부르키나파소", countryEn: "Burkina Faso", capital: "와가두구", capitalEn: "Ouagadougou", region: "아프리카" },
  { country: "카보베르데", countryEn: "Cabo Verde", capital: "프라이아", capitalEn: "Praia", region: "아프리카" },
  { country: "카메룬", countryEn: "Cameroon", capital: "야운데", capitalEn: "Yaoundé", region: "아프리카" },
  { country: "적도기니", countryEn: "Equatorial Guinea", capital: "말라보", capitalEn: "Malabo", region: "아프리카" },
  { country: "가봉", countryEn: "Gabon", capital: "리브르빌", capitalEn: "Libreville", region: "아프리카" },
  { country: "상투메 프린시페", countryEn: "São Tomé and Príncipe", capital: "상투메", capitalEn: "São Tomé", region: "아프리카" },
  { country: "앙골라", countryEn: "Angola", capital: "루안다", capitalEn: "Luanda", region: "아프리카" },
  { country: "잠비아", countryEn: "Zambia", capital: "루사카", capitalEn: "Lusaka", region: "아프리카" },
  { country: "짐바브웨", countryEn: "Zimbabwe", capital: "하라레", capitalEn: "Harare", region: "아프리카" },
  { country: "말라위", countryEn: "Malawi", capital: "릴롱궤", capitalEn: "Lilongwe", region: "아프리카" },
  { country: "모잠비크", countryEn: "Mozambique", capital: "마푸투", capitalEn: "Maputo", region: "아프리카" },
  { country: "보츠와나", countryEn: "Botswana", capital: "가보로네", capitalEn: "Gaborone", region: "아프리카" },
  { country: "나미비아", countryEn: "Namibia", capital: "빈트후크", capitalEn: "Windhoek", region: "아프리카" },
  { country: "남아프리카공화국", countryEn: "South Africa", capital: "프리토리아", capitalEn: "Pretoria", region: "아프리카", alt: ["케이프타운", "블룸폰테인"] },
  { country: "에스와티니", countryEn: "Eswatini", capital: "음바바네", capitalEn: "Mbabane", region: "아프리카" },
  { country: "레소토", countryEn: "Lesotho", capital: "마세루", capitalEn: "Maseru", region: "아프리카" },
  { country: "마다가스카르", countryEn: "Madagascar", capital: "안타나나리보", capitalEn: "Antananarivo", region: "아프리카" },
  { country: "모리셔스", countryEn: "Mauritius", capital: "포트루이스", capitalEn: "Port Louis", region: "아프리카" },
  { country: "세이셸", countryEn: "Seychelles", capital: "빅토리아", capitalEn: "Victoria", region: "아프리카" },
  { country: "코모로", countryEn: "Comoros", capital: "모로니", capitalEn: "Moroni", region: "아프리카" },

  // ── 북아메리카 ──────────────────────────────────────────
  { country: "미국", countryEn: "United States", capital: "워싱턴 D.C.", capitalEn: "Washington, D.C.", region: "북아메리카", alt: ["워싱턴", "워싱턴DC"] },
  { country: "캐나다", countryEn: "Canada", capital: "오타와", capitalEn: "Ottawa", region: "북아메리카" },
  { country: "멕시코", countryEn: "Mexico", capital: "멕시코시티", capitalEn: "Mexico City", region: "북아메리카" },
  { country: "과테말라", countryEn: "Guatemala", capital: "과테말라시티", capitalEn: "Guatemala City", region: "북아메리카", alt: ["과테말라"] },
  { country: "벨리즈", countryEn: "Belize", capital: "벨모판", capitalEn: "Belmopan", region: "북아메리카" },
  { country: "온두라스", countryEn: "Honduras", capital: "테구시갈파", capitalEn: "Tegucigalpa", region: "북아메리카" },
  { country: "엘살바도르", countryEn: "El Salvador", capital: "산살바도르", capitalEn: "San Salvador", region: "북아메리카" },
  { country: "니카라과", countryEn: "Nicaragua", capital: "마나과", capitalEn: "Managua", region: "북아메리카" },
  { country: "코스타리카", countryEn: "Costa Rica", capital: "산호세", capitalEn: "San José", region: "북아메리카" },
  { country: "파나마", countryEn: "Panama", capital: "파나마시티", capitalEn: "Panama City", region: "북아메리카", alt: ["파나마"] },
  { country: "쿠바", countryEn: "Cuba", capital: "아바나", capitalEn: "Havana", region: "북아메리카" },
  { country: "자메이카", countryEn: "Jamaica", capital: "킹스턴", capitalEn: "Kingston", region: "북아메리카" },
  { country: "아이티", countryEn: "Haiti", capital: "포르토프랭스", capitalEn: "Port-au-Prince", region: "북아메리카" },
  { country: "도미니카공화국", countryEn: "Dominican Republic", capital: "산토도밍고", capitalEn: "Santo Domingo", region: "북아메리카" },
  { country: "바하마", countryEn: "Bahamas", capital: "나소", capitalEn: "Nassau", region: "북아메리카" },
  { country: "바베이도스", countryEn: "Barbados", capital: "브리지타운", capitalEn: "Bridgetown", region: "북아메리카" },
  { country: "트리니다드 토바고", countryEn: "Trinidad and Tobago", capital: "포트오브스페인", capitalEn: "Port of Spain", region: "북아메리카" },
  { country: "앤티가 바부다", countryEn: "Antigua and Barbuda", capital: "세인트존스", capitalEn: "St. John's", region: "북아메리카" },
  { country: "세인트키츠 네비스", countryEn: "Saint Kitts and Nevis", capital: "바스테르", capitalEn: "Basseterre", region: "북아메리카" },
  { country: "세인트루시아", countryEn: "Saint Lucia", capital: "캐스트리스", capitalEn: "Castries", region: "북아메리카" },
  { country: "세인트빈센트 그레나딘", countryEn: "Saint Vincent and the Grenadines", capital: "킹스타운", capitalEn: "Kingstown", region: "북아메리카" },
  { country: "그레나다", countryEn: "Grenada", capital: "세인트조지스", capitalEn: "St. George's", region: "북아메리카" },
  { country: "도미니카연방", countryEn: "Dominica", capital: "로조", capitalEn: "Roseau", region: "북아메리카" },

  // ── 남아메리카 ──────────────────────────────────────────
  { country: "브라질", countryEn: "Brazil", capital: "브라질리아", capitalEn: "Brasília", region: "남아메리카" },
  { country: "아르헨티나", countryEn: "Argentina", capital: "부에노스아이레스", capitalEn: "Buenos Aires", region: "남아메리카" },
  { country: "칠레", countryEn: "Chile", capital: "산티아고", capitalEn: "Santiago", region: "남아메리카" },
  { country: "우루과이", countryEn: "Uruguay", capital: "몬테비데오", capitalEn: "Montevideo", region: "남아메리카" },
  { country: "파라과이", countryEn: "Paraguay", capital: "아순시온", capitalEn: "Asunción", region: "남아메리카" },
  { country: "볼리비아", countryEn: "Bolivia", capital: "수크레", capitalEn: "Sucre", region: "남아메리카", alt: ["라파스"] },
  { country: "페루", countryEn: "Peru", capital: "리마", capitalEn: "Lima", region: "남아메리카" },
  { country: "에콰도르", countryEn: "Ecuador", capital: "키토", capitalEn: "Quito", region: "남아메리카" },
  { country: "콜롬비아", countryEn: "Colombia", capital: "보고타", capitalEn: "Bogotá", region: "남아메리카" },
  { country: "베네수엘라", countryEn: "Venezuela", capital: "카라카스", capitalEn: "Caracas", region: "남아메리카" },
  { country: "가이아나", countryEn: "Guyana", capital: "조지타운", capitalEn: "Georgetown", region: "남아메리카" },
  { country: "수리남", countryEn: "Suriname", capital: "파라마리보", capitalEn: "Paramaribo", region: "남아메리카" },

  // ── 오세아니아 ──────────────────────────────────────────
  { country: "오스트레일리아", countryEn: "Australia", capital: "캔버라", capitalEn: "Canberra", region: "오세아니아" },
  { country: "뉴질랜드", countryEn: "New Zealand", capital: "웰링턴", capitalEn: "Wellington", region: "오세아니아" },
  { country: "파푸아뉴기니", countryEn: "Papua New Guinea", capital: "포트모르즈비", capitalEn: "Port Moresby", region: "오세아니아" },
  { country: "피지", countryEn: "Fiji", capital: "수바", capitalEn: "Suva", region: "오세아니아" },
  { country: "솔로몬제도", countryEn: "Solomon Islands", capital: "호니아라", capitalEn: "Honiara", region: "오세아니아" },
  { country: "바누아투", countryEn: "Vanuatu", capital: "포트빌라", capitalEn: "Port Vila", region: "오세아니아" },
  { country: "사모아", countryEn: "Samoa", capital: "아피아", capitalEn: "Apia", region: "오세아니아" },
  { country: "통가", countryEn: "Tonga", capital: "누쿠알로파", capitalEn: "Nuku'alofa", region: "오세아니아" },
  { country: "키리바시", countryEn: "Kiribati", capital: "타라와", capitalEn: "Tarawa", region: "오세아니아" },
  { country: "투발루", countryEn: "Tuvalu", capital: "푸나푸티", capitalEn: "Funafuti", region: "오세아니아" },
  { country: "나우루", countryEn: "Nauru", capital: "야렌", capitalEn: "Yaren", region: "오세아니아" },
  { country: "마셜제도", countryEn: "Marshall Islands", capital: "마주로", capitalEn: "Majuro", region: "오세아니아" },
  { country: "미크로네시아연방", countryEn: "Micronesia", capital: "팔리키르", capitalEn: "Palikir", region: "오세아니아" },
  { country: "팔라우", countryEn: "Palau", capital: "응게룰무드", capitalEn: "Ngerulmud", region: "오세아니아" }
];

const REGIONS = ["아시아", "유럽", "아프리카", "북아메리카", "남아메리카", "오세아니아"];
